begin;

-- A pending organization account could be provisioned again when GoTrue
-- updated auth.users during a later sign-in. Restore only untouched pending
-- shells whose membership and experience were generated by that bug.
do $$
declare
  cleanup_person_id bigint;
begin
  for cleanup_person_id in
    select account.person_id
    from public.portal_accounts as account
    where account.onboarding_status = 'pending'
      and (
        select count(*)
        from public.portal_accounts as sibling_account
        where sibling_account.person_id = account.person_id
      ) = 1
      and not exists (
        select 1 from public.access_requests where person_id = account.person_id
      )
      and not exists (
        select 1 from public.historical_membership_requests where person_id = account.person_id
      )
      and not exists (
        select 1 from public.team_memberships where person_id = account.person_id
      )
      and not exists (
        select 1 from public.external_accounts where person_id = account.person_id
      )
      and not exists (
        select 1 from public.portal_administrators where person_id = account.person_id
      )
      and not exists (
        select 1
        from public.profile_experiences as experience
        where experience.person_id = account.person_id
          and experience.source <> 'membership_default'
      )
  loop
    delete from public.profile_experiences
    where person_id = cleanup_person_id
      and source = 'membership_default';

    delete from public.memberships
    where person_id = cleanup_person_id;
  end loop;
end;
$$;

create or replace function private.provision_portal_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_email text;
  matched_person_id bigint;
  matched_organization_id bigint;
  existing_onboarding_status text;
  display_name text;
  created_new_person boolean := false;
  new_onboarding_status text := 'complete';
begin
  normalized_email := lower(new.email);

  if normalized_email is null
    or new.email_confirmed_at is null
    or not (
      coalesce(new.raw_app_meta_data ->> 'provider', '') = 'google'
      or coalesce(new.raw_app_meta_data -> 'providers', '[]'::jsonb) ? 'google'
    )
  then
    return new;
  end if;

  display_name := coalesce(
    nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''),
    nullif(btrim(new.raw_user_meta_data ->> 'name'), '')
  );

  select account.person_id, account.onboarding_status
  into matched_person_id, existing_onboarding_status
  from public.portal_accounts as account
  where account.auth_user_id = new.id;

  if matched_person_id is null then
    select person_email.person_id
    into matched_person_id
    from public.person_emails as person_email
    where person_email.email = normalized_email;
  end if;

  if matched_person_id is null then
    insert into public.people (
      full_name,
      portal_access_status,
      source
    ) values (display_name, 'active', 'google')
    returning id into matched_person_id;
    created_new_person := true;
  else
    update public.people
    set full_name = coalesce(full_name, display_name),
        portal_access_status = case
          when portal_access_status = 'unclaimed' then 'active'
          else portal_access_status
        end
    where id = matched_person_id;
  end if;

  select domain.organization_id
  into matched_organization_id
  from private.organization_domains as domain
  join public.organizations as organization
    on organization.id = domain.organization_id
  where domain.domain = split_part(normalized_email, '@', 2)
    and organization.status = 'active';

  if existing_onboarding_status = 'pending'
    or (created_new_person and matched_organization_id is not null)
  then
    new_onboarding_status := 'pending';
  end if;

  insert into public.person_emails (
    person_id,
    email,
    email_type,
    is_primary,
    source
  ) values (
    matched_person_id,
    normalized_email,
    case when matched_organization_id is not null then 'organization' else 'personal' end,
    not exists (
      select 1
      from public.person_emails as existing_email
      where existing_email.person_id = matched_person_id
        and existing_email.is_primary
    ),
    'google'
  )
  on conflict (email) do nothing;

  insert into public.portal_accounts (
    auth_user_id,
    person_id,
    account_email,
    onboarding_status
  ) values (
    new.id,
    matched_person_id,
    normalized_email,
    new_onboarding_status
  )
  on conflict (auth_user_id) do update
  set account_email = excluded.account_email,
      last_seen_at = now();

  if matched_organization_id is not null and new_onboarding_status = 'complete' then
    insert into public.memberships (
      person_id,
      organization_id,
      role,
      status,
      provisioning_method
    ) values (
      matched_person_id,
      matched_organization_id,
      'member',
      'active',
      'domain'
    )
    on conflict (person_id, organization_id) do nothing;
  end if;

  return new;
end;
$$;

revoke all on function private.provision_portal_user() from public, anon, authenticated;

commit;
